spring:

  #注： 切换数据库时需要将项目根目录中的.init文件删除再重启
  # <<=======内置H2数据库连接设置开始==========
  #  jpa:
  #    show-sql: false
  #    hibernate:
  #      ddl-auto: update
  #    properties:
  #      hibernate:
  #        format_sql: true
  #  datasource:
  #    type: com.zaxxer.hikari.HikariDataSource
  #    driverClassName: org.h2.Driver
  #    url: jdbc:h2:./data/iotkit;MODE=MySQL
  #    username: sa
  #    password: 123456
  #    hikari:
  #      connection-timeout: 5000
  #      idle-timeout: 30000 # 经过idle-timeout时间如果连接还处于空闲状态, 该连接会被回收
  #      min-idle: 5 # 池中维护的最小空闲连接数, 默认为 10 个
  #      max-pool-size: 16 # 池中最大连接数, 包括闲置和使用中的连接, 默认为 10 个
  #      max-lifetime: 60000 # 如果一个连接超过了时长，且没有被使用, 连接会被回收
  #      is-auto-commit: true
  #    # 内置h2 web console设置
  #    platform: h2
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2
  #      settings:
  #        web-allow-others: true
  #=======内置H2数据库连接设置结束==========>>

  # <<==========mysql配置开始==============
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
    url: jdbc:mysql://127.0.0.1:3306/iotkit?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    hikari:
      connection-timeout: 5000
      idle-timeout: 30000 # 经过idle-timeout时间如果连接还处于空闲状态, 该连接会被回收
      min-idle: 5 # 池中维护的最小空闲连接数, 默认为 10 个
      max-pool-size: 16 # 池中最大连接数, 包括闲置和使用中的连接, 默认为 10 个
      max-lifetime: 60000 # 如果一个连接超过了时长，且没有被使用, 连接会被回收
      is-auto-commit: true
  # ============mysql配置结束============>>

  #<<================es时序数据配置开始===============
#  elasticsearch:
#    embedded:
#      # 是否启用内部es
#      enabled: true
#      port: 9200
#    rest:
#      #使用内置es的配置
#      #uris: http://elasticsearch:9200
#      uris: http://127.0.0.1:9200
#      username:
#      password:
#      connection-timeout: 10s
  #================es时序数据配置结束===============>>

  #<<===========tdengine时序数据库配置开始============
  td-datasource:
    url: jdbc:TAOS-RS://127.0.0.1:6041/iotkit?timezone=UTC-8&charset=UTF-8&locale=en_US.UTF-8
    username: root
    password: taosdata
    driverClassName: com.taosdata.jdbc.rs.RestfulDriver
  #===========tdengine时序数据库配置开始============>>


  #<<===========iotdb时序数据库配置开始============
  #  iotdb-datasource:
  #    host: 127.0.0.1
  #    port: 6667
  #    username: root
  #    password: root
  #===========tdengine时序数据库配置开始============>>

  redis:
    #使用内置redis的配置
    embedded:
      enabled: true
    #host: redis
    host: 127.0.0.1
    port: 6378
    database: 0

  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
#  profiles:
#    active: mysql

#application.yml中打开注释支持rocketMq作为消息总线，pom.xml中打开注释使用rocketmq消息总线
#rocketmq:
#  name-server: 172.16.1.113:9876
#  producer:
#        group: iotkit

#图片存储用的是阿里云oss，如果需要上传产品图片才需要配置
aliyun:
  bucketId:
  endpoint:
  accessKeyId:
  accessKeySecret:

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

captcha:
  enable: true
  # 页面 <参数设置> 可开启关闭 验证码校验
  # 验证码类型 math 数组计算 char 字符验证
  type: MATH
  # line 线段干扰 circle 圆圈干扰 shear 扭曲干扰
  category: CIRCLE
  # 数字验证码位数
  numberLength: 1
  # 字符验证码长度
  charLength: 4

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# openapi配置
openapi:
  appid: 123456789
  password: 123456

oss:
  region: xxxxx
  endpoint: xxxxx
  accessKey: xxxxx
  secretKey: xxxxx
  buckName: xxxx

#微信小程序配置
weixin:
  appid: xx
  secret: xx
  authUrl: xx

websocket:
  enabled: true
  path: /websocket
  allowedOrigins: '*'

#init:
#  data:
#    flag: false

# 插件配置
plugin:
  # 独立部署模式
  standalone: false
  ip: localhost
  runMode: dev # 运行模式, 开发环境: dev; 生产环境: prod。dev环境下，只适用于在idea环境下开发调试，prod环境只能加载打包的插件，比如jar、zip等
  mainPackage: cc.iotkit
  # 如果配置是 windows 下路径, mac、linux 自行修改
  pluginPath:
    - ./data/plugins


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cc.iotkit.*.model
  global-config:
    # 数据库相关配置
    db-config:
      # ID自增
      id-type: AUTO
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
#文件服务配置
storage:
  enabled: true
  config:
    # 存储类型：local、aliyun
    type: local
    # 访问域名
    domain: http://localhost:8083/sys
    # 配置访问前缀
    prefix:
  local:
    # 本地上传路径
    path: /bigdata/deploy/ant-data/upload